.cortex: &cortex
  image: vrunali/cortex:centos
  stage: replace_cortex
  script: 
#     - cd /etc/yum.repos.d/
#     - sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
#     - sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
#     - yum update -y
#     - yum install -y python3
#     - pip3 install requests
#     - yum -y install git
#     - curl –sL https://rpm.nodesource.com/setup_10.x | sudo bash -
#     - yum install –y nodejs
    - mkdir cortex
    - cd cortex
    - git clone https://github.com/Cimpress/cimpress-cortex.git
    - cd cimpress-cortex
    # - cd gitlab-ci-templates
    - ls -la
    - envsubst < cortex.yml > cortex1.yml
    - mv cortex1.yml cortex.yml
    - ls -la
    - cd ..
    - git clone https://cortex-git:${CORTEX_JOB_TOKEN}@gitlab.com/${SERVICE_REPO}.git
    - cd $SERVICE_NAME
    - git checkout -b cortex-implementation
    - mkdir -p scripts
    - cp ../cimpress-cortex/cortex.yml cortex.yml
    - cp -rf ../cimpress-cortex/custom/* scripts/
    - ls scripts/
    - chmod 777 scripts/rfc_custom_data.py
    - python3 scripts/rfc_custom_data.py
    - git config user.email "sa_ecom-gitlab-integration@cimpress.com"
    - git config user.name "sa_ecom-gitlab-integration"
    - git add -f cortex.yml scripts/
    - git commit -m "ADD cortex.yml and customdata scripts"
    - git push -u -f origin cortex-implementation
